In [1]:
import os, stat
print("test")

test


In [2]:
#HMM

import pandas as pd
import mdtraj, os, cython, msmbuilder, math, scipy
from mdtraj.utils import timing
import numpy as np
from scipy import stats
from scipy.spatial.distance import cdist
from scipy.cluster.vq import *
from scipy.cluster.vq import kmeans, vq
from scipy.spatial.distance import cdist
import matplotlib.pyplot as plt
from mpl_toolkits.axes_grid1 import make_axes_locatable
from mpl_toolkits.mplot3d import Axes3D
import glob
import datetime 
%matplotlib
direname = os.chdir('C://Users//vknguyen//Desktop//Python//!analyzedTPP//')

#formatting
fontsize = 36
fontsize2 = 32
linewidth1 = 4
linewidth2 = 10
linewidth3 = 5
linewidth4 = 20
linewidth5 = 3
font1 = 'arial'

alpha = 0.9
alpha2 = 0.7
alpha3 = 0.5
circle = 500
circle2 = 1000 
ticklength = 20
tickwidth = 1
SBcolor = '#1874cd'
WBcolor = '#6dc066'
FFcolor = '#885ead'
SBcolordark = '#003891'
WBcolordark = '#22741B'
FFcolordark = '#3E1760'
grey = '#cccccc'
black = '#000000'
noTPPcolor = '#EEC900'
Tcolor = '#ff4444'
fretlim_max = 1.0
fretlim_min = 0


binwidth = 0.005
bin = np.arange(fretlim_min,fretlim_max,binwidth)

from msmbuilder.example_datasets import load_doublewell
import msmbuilder.cluster
from msmbuilder.cluster import NDGrid
from msmbuilder.msm import BayesianMarkovStateModel, MarkovStateModel
from msmbuilder.featurizer import SuperposeFeaturizer
from msmbuilder.hmm.ghmm import GaussianFusionHMM
from msmbuilder.dataset import dataset
import msmbuilder.hmm

%matplotlib
pulls_list = os.listdir(direname)
fret_list = []
pull_list = []
refoldtime = 3.0

for p in pulls_list:
    if "WT2at" in p and "refold" in p and "up" not in p and datetime.datetime.strptime(p[:10], "%Y.%m.%d") < datetime.datetime(2014, 12, 20, 0, 0):#and str(refoldtime) in p
    #if "WT2at" in p and "refold" in p and str(refoldtime) in p and "up" not in p and datetime.datetime.strptime(p[:10], "%Y.%m.%d") < datetime.datetime(2014, 12, 20, 0, 0):
        if ".fret" in p:
            fret_list.append(p)
        if ".str" in p:
            pull_list.append(p)

print(len(fret_list))
pull_list.sort
fret_list.sort
n_features = 1

n_states = 4

plt.close('all')
timescales = []
# Get a list of all filenames to process
filenames = fret_list#glob.glob("./*.fret")
ext = []
f = []

X = []  # List that will contain all fret traces
Time = []
X2 = []
Time2 = []
x_length_list = []
x_exptime_list = []
b=7
for filename in fret_list[0:20]:
        dataset = pd.read_table(filename, comment="#")  # Read file with pandas reader    
        x_i = dataset["FRET"]  # Grab column of FRET values
        x_i = x_i.values  # Convert from pandas series to numpy array   
        x_i = x_i[:, np.newaxis]  # Convert from 1D array to 2D array of shape (traj_len, 1)
        x_t = dataset["time"]  # Grab column of FRET values
        x_t = x_t.values  # Convert from pandas series to numpy array   
        x_t = x_t[:, np.newaxis]  # Convert from 1D array to 2D array of shape (traj_len, 1)
        x_length = len(x_i)
        x_exptime = x_t[0]
        x_length_list.append(x_length)
        X.append(x_i)  # Add to dataset
        X2.extend(x_i)
        Time.append(x_t)  # Add to dataset
        Time2.extend(x_t)

#trans_init = [[0.3, 0.65, 0.0025, 0.0025],[ 0.0025, 0.5, 0.5, 0.0025],[0.0025, 0.0025,0.7, 0.25],[0.0049, 0.005, 0.0001, 0.99]]
model = msmbuilder.hmm.GaussianFusionHMM(n_states, n_features)
model.fit(X)
print("love")
while True:
    if np.min(model.means_) != model.means_[0]:
        print(np.min(model.means_), model.means_[0], np.max(model.means_),model.means_[-1])
        model = msmbuilder.hmm.GaussianFusionHMM(n_states, n_features)
        model.fit(X)
    else:#if np.min(model.means_) == model.means_[0] and np.max(model.means_) == model.means_[-1]:
        break

    
timescales.append(model.timescales_)   

print(model.means_,"means")
print(model.timescales_)               

_0 = max(model.means_)
_1 = np.median(model.means_)
_2 = min(model.means_)
_3 = min(model.means_)

trans = np.array(model.transmat_)
print("0>1",trans[0][1],0.05/trans[0][1],"s \n",
     "1>0", trans[1][0],0.05/trans[1][0],"s \n",
     "1>2", trans[1][2],0.05/trans[1][2],"s \n",
     "2>1", trans[2][1],0.05/trans[2][1],"s \n",
     "2>3", trans[2][3],0.05/trans[2][3],"s \n",
     "3>2", trans[3][2],0.05/trans[3][2],"s \n")
''',
     "3>4", trans[3][4],0.05/trans[3][4],"s \n",
     "4>3", trans[4][3],0.05/trans[4][3],"s \n",)'''



Using matplotlib backend: Qt4Agg
Using matplotlib backend: Qt4Agg
184
love
0.179762 [ 0.40865752] 0.706034 [ 0.40865752]
0.179762 [ 0.40865752] 0.706034 [ 0.706034]
[[ 0.17976196]
 [ 0.40865752]
 [ 0.706034  ]
 [ 0.40865752]] means
[ 12.38062      8.47134686]
0>1 0.0555531 0.900040308701 s 
 1>0 0.0258551 1.93385418029 s 
 1>2 0.0377201 1.32555416796 s 
 2>1 0.0362444 1.37952346329 s 
 2>3 0.00814805 6.13643970516 s 
 3>2 0.31722 0.157619361049 s 



',\n     "3>4", trans[3][4],0.05/trans[3][4],"s \n",\n     "4>3", trans[4][3],0.05/trans[4][3],"s \n",)'

In [3]:
#2
print(np.array(model.populations_))
print(np.array(model.vars_))
print(np.array(model.transmat_))


[ 0.18374996  0.3948108   0.41088533  0.01055392]
[[ 0.01997279]
 [ 0.00914105]
 [ 0.01389067]
 [ 5.29896402]]
[[  8.93403590e-01   5.55530675e-02   1.20784063e-02   3.89649644e-02]
 [  2.58551035e-02   9.36307847e-01   3.77200730e-02   1.17002717e-04]
 [  5.40152378e-03   3.62443998e-02   9.50206041e-01   8.14804714e-03]
 [  6.78403139e-01   4.37694695e-03   3.17219913e-01   5.28851947e-22]]


In [4]:
#3
trans = np.array(model.transmat_)
print("0>1",trans[0][1],0.05/trans[0][1],"s \n",
     "1>0", trans[1][0],0.05/trans[1][0],"s \n",
     "1>2", trans[1][2],0.05/trans[1][2],"s \n",
     "2>1", trans[2][1],0.05/trans[2][1],"s \n",
     "2>3", trans[2][3],0.05/trans[2][3],"s \n",
     "3>2", trans[3][2],0.05/trans[3][2],"s \n")
''',
     "3>4", trans[3][4],0.05/trans[3][4],"s \n",
     "4>3", trans[4][3],0.05/trans[4][3],"s \n",)'''
np.save("transition dwell times for "+str(n_states) + " states", ".npy")

0>1 0.0555531 0.900040308701 s 
 1>0 0.0258551 1.93385418029 s 
 1>2 0.0377201 1.32555416796 s 
 2>1 0.0362444 1.37952346329 s 
 2>3 0.00814805 6.13643970516 s 
 3>2 0.31722 0.157619361049 s 



In [5]:
#4 plot probabiity of state eassignment throughout data collection
plt.close('all')
#print(pull_list[3])
score_list = []
for i,x in enumerate(model.predict(X)[1:]):
    for item in x:
        score_list.extend(np.array(item))
plt.figure()#"trajectory refold time "+ str(refoldtime)+"s, "+str(n_states) + " states")    

frame_n =int(len(X)/0.05)
states = []
for i in range(frame_n):
    states.append(score_list[i::frame_n])

counts = []
for i in range(frame_n):
     counts.append(np.histogram(states[i], bins=n_states)[0])

counts = np.array(counts)

for i in range(n_states):
    plt.plot(counts[:,i]/len(X))
#plt.plot(Time2,X2,".")
#plt.ylim(-0.1, 1.1)
plt.rcParams['svg.fonttype'] = 'none'
print(len(score_list))
        

1700


In [6]:
#HHM score for each state versus FRET values
plt.close('all')
#plt.scatter(score_list,X)
refoldtime = (5970/3680)
catTime = np.arange(0,len(X)*(1700/400), 0.05)
#for thing in map(lambda i: model.means_[i], np.array(score_list)):
#    print(thing[0])
statefret = []
for point in score_list:
    statefret.append(model.means_[point])
print(refoldtime,len(catTime) , len(score_list),len(X), len(X2))

plt.figure("model on data refold time "+ str(refoldtime)+"s, "+str(n_states) + " states")    
plt.plot(catTime,statefret,"r-") 
plt.scatter(catTime,X2, color = "blue")
plt.ylim(-0.1,1.2)
print(len(statefret), len(X2))
x2_std = np.std(X2)
print("p_value = ", np.sum((np.array(X2)-np.array(statefret))**2)/(len(score_list)*(x2_std)**2))
chisq_value, p_value = scipy.stats.chisquare(X2,statefret, ddof = 6)
print(chisq_value, float(p_value))


1.622282608695652 1700 1700 20 1700
1700 1700
p_value =  0.646934733139
[ 309.22566531] 1.0


In [37]:
#dwell times
count_0_list = []
count_1_list = []
count_2_list = []
count_3_list = []
count_4_list = []

        
#histo, bino = np.histogram(score_list, n_states)
#print(histo)

kFFWB = []
kWBFF = []
kWBSB = []
kSBWB = []
k34 = []
k43 = []
kFFUF = []
kUFFF = []

kFFWB_force = []
kWBFF_force = []
kWBSB_force = []
kSBWB_force = []

exposure_time = 0.05
n = 1
p_count = 0

for i,t in enumerate(score_list[:-1]):
    if score_list[i] == score_list[i+1] and i !=len(score_list)-n:
        p_count +=1
    elif score_list[i] != score_list[i+1] or i ==len(score_list)-n:
        if score_list[i] == 4:
            p_count +=1
            count_4_list.append(p_count * float(exposure_time))
            if score_list[i]== 4 and score_list[i+1] == 3:
                k43.append(p_count * float(exposure_time))
        
        elif score_list[i] == 3:
            p_count +=1
            count_3_list.append(p_count * float(exposure_time))
            if score_list[i]== 3 and score_list[i+1] == 2:
                kSBWB.append(p_count * float(exposure_time))
            elif score_list[i]== 3 and score_list[i+1] == 4:
                k34.append(p_count * float(exposure_time))  
                
        elif score_list[i] == 2:
            p_count +=1
            count_2_list.append(p_count * float(exposure_time))
            if score_list[i]== 2 and score_list[i+1] == 1:
                kWBFF.append(p_count * float(exposure_time))
            elif score_list[i] == 2 and score_list[i+1] == 3:
                kWBSB.append(p_count * float(exposure_time))
            #print "WB", Time[i], p_count

        elif score_list[i] == 1:
            p_count +=1
            count_1_list.append(p_count * float(exposure_time))
            if score_list[i] == 1 and score_list[i+1] ==2:
                kFFWB.append(p_count * float(exposure_time))
            elif score_list[i] == 1 and score_list[i+1] == 0:
                kFFUF.append(p_count * float(exposure_time))
            
        elif score_list[i] == 0:
            p_count +=1
            count_0_list.append(p_count * float(exposure_time))
            if score_list[i]== 0 and score_list[i+1] == 1:
                kUFFF.append(p_count * float(exposure_time))

        elif score_list[i]:
            break
    
        p_count = 0
print("UFFF",np.mean(kUFFF), stats.sem(kUFFF),"\n",
      "FFUF",np.mean(kFFUF), stats.sem(kFFUF),"\n",
      "FFWB",np.mean(kFFWB), stats.sem(kFFWB),"\n", 
      "WBFF",np.mean(kWBFF), stats.sem(kWBFF),"\n", 
      "WBSB",np.mean(kWBSB), stats.sem(kWBSB),"\n", 
      "SBWB",np.mean(kSBWB), stats.sem(kSBWB),"\n", 
      "34",np.mean(k34), stats.sem(k34),"\n", 
      "43",np.mean(k43), stats.sem(k43),"\n", 
      "Refold, n", n_states)#refoldtime,


UFFF nan nan 
 FFUF nan nan 
 FFWB 1.21785714286 0.333998714499 
 WBFF 0.832352941176 0.226666263824 
 WBSB 0.05 4.90653893339e-18 
 SBWB 0.05 0.0 
 34 0.05 0.0 
 43 1.45 nan 
 Refold, n 5


c:\Users\vknguyen\AppData\Local\Continuum\Anaconda3\lib\site-packages\numpy\core\_methods.py:59: RuntimeWarning: Mean of empty slice.
  warnings.warn("Mean of empty slice.", RuntimeWarning)
c:\Users\vknguyen\AppData\Local\Continuum\Anaconda3\lib\site-packages\numpy\core\_methods.py:83: RuntimeWarning: Degrees of freedom <= 0 for slice
  warnings.warn("Degrees of freedom <= 0 for slice", RuntimeWarning)


In [36]:
#dwell times 2
bin_dwell = np.arange(0,5,0.05)
capsize1 = 1
plt.close('all')
plt.figure()
#plt.hist(kWBSB,bins = 10)
print ("UF",np.mean(count_0_list), stats.sem(count_0_list))
print ("FF",np.mean(count_1_list), stats.sem(count_1_list))
print ("WB",np.mean(count_2_list), stats.sem(count_2_list))
print ("SB",np.mean(count_3_list), stats.sem(count_3_list))


print ("kSBWB",np.mean(kSBWB), stats.sem(kSBWB))
print ("kWBSB",np.mean(kWBSB), stats.sem(kWBSB))
print ("kWBFF",np.mean(kWBFF), stats.sem(kWBFF))
print ("kFFWB",np.mean(kFFWB), stats.sem(kFFWB))
print ("kFFUF",np.mean(kFFUF), stats.sem(kFFUF))
print ("kUFFF",np.mean(kUFFF), stats.sem(kUFFF))

kSBWB_hist_ln = []
kWBFF_hist_ln = []
kWBSB_hist_ln = []
kFFWB_hist_ln = []
kUFFF_hist_ln = []


kSBWB_hist, kSBWB_bin = np.histogram(kSBWB, bins = bin_dwell)
kWBFF_hist, kWBFF_bin = np.histogram(kWBFF, bins = bin_dwell)
kWBSB_hist, kWBSB_bin = np.histogram(kWBSB, bins = bin_dwell)
kFFWB_hist, kFFWB_bin = np.histogram(kFFWB, bins = bin_dwell)
kUFFF_hist, kUFFF_bin = np.histogram(kUFFF, bins = bin_dwell)

for points1 in kSBWB_hist:
    a = np.log(points1)
    kSBWB_hist_ln.append(a)#red
    
for points2 in kWBSB_hist:
    b = np.log(points2)
    kWBSB_hist_ln.append(b)#blue

for points3 in kWBFF_hist:
    c = np.log(points3)
    kWBFF_hist_ln.append(c)#purple
    
for points4 in kFFWB_hist:
    d = np.log(points4)
    kFFWB_hist_ln.append(d)#green
    
for points5 in kUFFF_hist:
    e = np.log(points5)
    kUFFF_hist_ln.append(e)#green
    
print(kUFFF_hist)

kSBWB_width = 1 * (kSBWB_bin[1] - kSBWB_bin[0])
kSBWB_center = (kSBWB_bin[:-1] + kSBWB_bin[1:]) / 2
kWBFF_width = 1 * (kWBFF_bin[1] - kWBFF_bin[0])
kWBFF_center = (kWBFF_bin[:-1] + kWBFF_bin[1:]) / 2
kWBSB_width = 1 * (kWBSB_bin[1] - kWBSB_bin[0])
kWBSB_center = (kWBSB_bin[:-1] + kWBSB_bin[1:]) / 2
kFFWB_width = 1 * (kFFWB_bin[1] - kFFWB_bin[0])
kFFWB_center = (kFFWB_bin[:-1] + kFFWB_bin[1:]) / 2
kUFFF_width = 1 * (kUFFF_bin[1] - kUFFF_bin[0])
kUFFF_center = (kUFFF_bin[:-1] + kUFFF_bin[1:]) / 2


def func(x, a, c):
    return a*np.exp(c*x)
    if c*x == 1/0:
        pass
    

figure_kSBWB = plt.figure('kSBWB')
SBWB_line = plt.hist(kSBWB, bins = bin_dwell, color = Tcolor, label = 'kSBWB', alpha = 0.3)
menStd_SBWB = np.sqrt(kSBWB_hist)
plt.errorbar(kSBWB_center, kSBWB_hist, yerr=menStd_SBWB, linewidth=0, ecolor = black, elinewidth=capsize1)
start_fret = 2
slope_n = start_fret+6
slope_SBWB = (kSBWB_hist_ln[start_fret]-kSBWB_hist_ln[slope_n])/(kSBWB_center[start_fret]-kSBWB_center[slope_n])
print( slope_SBWB, "slope")
intercept_SBWB = np.exp(np.log(kSBWB_hist[start_fret])-slope_SBWB*exposure_time)
print( intercept_SBWB, "intercept adjusted SBWB")
kSBWBy = func(kSBWB_center[start_fret:],intercept_SBWB, slope_SBWB)
popt_SBWB, pcov_SBWB = scipy.optimize.curve_fit(func, kSBWB_center[start_fret:], kSBWBy)
exp_SBWB = func(kSBWB_center[start_fret:],popt_SBWB[0],popt_SBWB[1])
label_SBWB =  "kSBWB=", '%s' % float('%.4g' %-popt_SBWB[1]),  "$\t{s^{-1}}$", round(1000*(-popt_SBWB[1])**(-1),0), "ms"
plt.plot(kSBWB_center[start_fret:], exp_SBWB,'-',color =Tcolor,alpha = alpha2, linewidth=2)#, xlim=([minf-0.1, maxf+0.1]))
plt.legend([label_SBWB])#FFWB_line,WBSB_line,WBFF_line, SBWB_line),
plt.ylim(0,30)
plt.xlim(0,3)

start_fret = 1
slope_n = start_fret+10
figure_kWBFF = plt.figure('kWBFF')
WBFF_line = plt.hist(kWBFF, bins = bin_dwell, color = FFcolor, label = 'kWBFF', alpha = 0.3)
menStd_WBFF = np.sqrt(kWBFF_hist)
plt.errorbar(kWBFF_center, kWBFF_hist, yerr=menStd_WBFF, 
         linewidth=0, ecolor = black, elinewidth=capsize1,
         alpha = alpha2)
slope_WBFF = (kWBFF_hist_ln[start_fret]-kWBFF_hist_ln[slope_n])/(kWBFF_center[start_fret]-kWBFF_center[slope_n])
print( slope_WBFF, "slope", np.log(kWBFF_hist[start_fret]), "intercept")
intercept_WBFF = np.exp(np.log(kWBFF_hist[start_fret])-slope_WBFF*exposure_time)
print( intercept_WBFF, "intercept adjusted WBFF")
kWBFFy = func(kWBFF_center[start_fret:],intercept_WBFF, slope_WBFF)
popt_WBFF, pcov_WBFF = scipy.optimize.curve_fit(func, kWBFF_center[start_fret:], kWBFFy)
exp_WBFF = func(kWBFF_center[start_fret:],popt_WBFF[0],popt_WBFF[1])
label_WBFF =  "kWBFF=", '%s' % float('%.4g' %-popt_WBFF[1]),  "$\t{s^{-1}}$", round(1000*(-popt_WBFF[1])**(-1),0), "ms"
plt.plot(kWBFF_center[start_fret:], exp_WBFF,'-',color =FFcolor,alpha = alpha2, linewidth=2)#, xlim=([minf-0.1, maxf+0.1]))
plt.legend([label_WBFF])#FFWB_line,WBSB_line,WBFF_line, SBWB_line),
plt.ylim(0,30)
plt.xlim(0,3)

start_fret = 2
slope_n = start_fret+6
figure_kWBSB = plt.figure('kWBSB')
WBSB_line = plt.hist(kWBSB, bins = bin_dwell, color = SBcolor, label = 'kWBSB', alpha = 0.3)
menStd_WBSB = np.sqrt(kWBSB_hist)
plt.errorbar(kWBSB_center, kWBSB_hist, yerr=menStd_WBSB, linewidth=0, ecolor = black, elinewidth=capsize1)
slope_WBSB = (kWBSB_hist_ln[start_fret]-kWBSB_hist_ln[slope_n])/(kWBSB_center[start_fret]-kWBSB_center[slope_n])
print( slope_WBSB, "slope", np.log(kWBSB_hist[start_fret]), "intercept")
intercept_WBSB = np.exp(np.log(kWBSB_hist[start_fret])-slope_WBSB*exposure_time)
print( intercept_WBSB, "intercept adjusted WBSB")
kWBSBy = func(kWBSB_center[start_fret:],intercept_WBSB, slope_WBSB)
popt_WBSB, pcov_WBSB = scipy.optimize.curve_fit(func, kWBSB_center[start_fret:], kWBSBy)
exp_WBSB = func(kWBSB_center[start_fret:],popt_WBSB[0],popt_WBSB[1])
label_WBSB =  "kWBSB=", '%s' % float('%.4g' %-popt_WBSB[1]),  "$\t{s^{-1}}$", round(1000*(-popt_WBSB[1])**(-1),0), "ms"
plt.plot(kWBSB_center[start_fret:], exp_WBSB,'-',color =SBcolor,alpha = alpha2, linewidth=2)#, xlim=([minf-0.1, maxf+0.1]))
plt.legend([label_WBSB])#FFWB_line,WBSB_line,WBFF_line, SBWB_line),
plt.ylim(0,30)
plt.xlim(0,3)

figure_kFFWB = plt.figure('kFFWB')
FFWB_line = plt.hist(kFFWB, bins = bin_dwell, color = WBcolor, label = 'kFFWB', alpha = 0.3)
menStd_FFWB = np.sqrt(kFFWB_hist)
plt.errorbar(kFFWB_center, kFFWB_hist, yerr=menStd_FFWB, 
         linewidth=0, ecolor = black, elinewidth=capsize1,
         alpha = alpha2)
start_fret = 2
slope_n = start_fret+5
slope_FFWB = (kFFWB_hist_ln[start_fret]-kFFWB_hist_ln[slope_n])/(kFFWB_center[start_fret]-kFFWB_center[slope_n])
print( slope_FFWB, "slope", np.log(kFFWB_hist[start_fret]), "intercept")
intercept_FFWB = np.exp(np.log(kFFWB_hist[start_fret])-slope_FFWB*exposure_time)
print( intercept_FFWB, "intercept adjusted FFWB")
kFFWBy = func(kFFWB_center[start_fret:],intercept_FFWB, slope_FFWB)
popt_FFWB, pcov_FFWB = scipy.optimize.curve_fit(func, kFFWB_center[start_fret:], kFFWBy)
exp_FFWB = func(kFFWB_center[start_fret:],popt_FFWB[0],popt_FFWB[1])
label_FFWB =  "kFFWB=", '%s' % float('%.4g' %-popt_FFWB[1]),  "$\t{s^{-1}}$", round(1000*(-popt_FFWB[1])**(-1),0), "ms"
plt.plot(kFFWB_center[start_fret:], exp_FFWB,'-',color =WBcolor,alpha = alpha2, linewidth=2)#, xlim=([minf-0.1, maxf+0.1]))
plt.legend([label_FFWB])#FFWB_line,WBSB_line,WBFF_line, SBWB_line),
plt.ylim(0,30)
plt.xlim(0,3)



#plt.legend((SBWB_line, WBFF_line))
#plt.annotate(str(np.mean(kSBWB)), str(np.mean(kWBSB)), [1.5, 140])
print( len(kUFFF), len(kFFWB), len(kWBFF), len(kWBSB), len(kSBWB))

#label_UFFF =  "kUFFF=", '%s' % float('%.4g' %-popt_UFFF[1]),  "$\t{s^{-1}}$", round(1000*(-popt_UFFF[1])**(-1),0), "ms"

print( label_FFWB)
print( label_WBSB)
print( label_WBFF)
print( label_SBWB)

plt.figure()
def func_ln(x, a, c):
    return a+c*x
    if c*x == 1/0:
        pass

SBWB_line = plt.plot(kSBWB_center[start_fret:], kSBWB_hist_ln[start_fret:], "o", color = Tcolor, label = 'kSBWB')
WBFF_line = plt.plot(kWBFF_center[start_fret:], kWBFF_hist_ln[start_fret:], "o", color = FFcolor, label = 'kWBFF')
WBSB_line = plt.plot(kWBSB_center[start_fret:], kWBSB_hist_ln[start_fret:], "o", color = SBcolor, label = 'kWBSB')
FFWB_line = plt.plot(kFFWB_center[start_fret:], kFFWB_hist_ln[start_fret:], "o", color = WBcolor, label = 'kFFWB')
UFFF_line = plt.plot(kUFFF_center[start_fret:], kUFFF_hist_ln[start_fret:], "o", color = Tcolor, label = 'kUFFF')

plt.ylim(0)
plt.xlim(0,2)


slope_UFFF = (kUFFF_hist_ln[start_fret]-kUFFF_hist_ln[slope_n])/(kUFFF_center[start_fret]-kUFFF_center[slope_n])
print( slope_UFFF, "slope", np.log(kUFFF_hist[start_fret]), "intercept")
intercept_UFFF = kUFFF_hist_ln[start_fret]-(slope_UFFF*exposure_time)
print( intercept_UFFF, "intercept adjusted FFWB")
try:
    kUFFFy = func_ln(kUFFF_center[start_fret:],intercept_UFFF, slope_UFFF)
    popt_UFFF, pcov_UFFF = scipy.optimize.curve_fit(func_ln, kUFFF_center[start_fret:], kUFFFy)
    exp_UFFF = func_ln(kUFFF_center[start_fret:],popt_UFFF[0],popt_UFFF[1])
    plt.plot(kUFFF_center[start_fret:], exp_UFFF,'-',color =WBcolor,alpha = alpha2, linewidth=2)#, xlim=([minf-0.1, maxf+0.1]))
except:
    pass
start_fret = 2
slope_n = start_fret+5
slope_FFWB = (kFFWB_hist_ln[start_fret]-kFFWB_hist_ln[slope_n])/(kFFWB_center[start_fret]-kFFWB_center[slope_n])
print( slope_FFWB, "slope", np.log(kFFWB_hist[start_fret]), "intercept")
intercept_FFWB = kFFWB_hist_ln[start_fret]-(slope_FFWB*exposure_time)
print( intercept_FFWB, "intercept adjusted FFWB")
kFFWBy = func_ln(kFFWB_center[start_fret:],intercept_FFWB, slope_FFWB)
popt_FFWB, pcov_FFWB = scipy.optimize.curve_fit(func_ln, kFFWB_center[start_fret:], kFFWBy)
exp_FFWB = func_ln(kFFWB_center[start_fret:],popt_FFWB[0],popt_FFWB[1])
plt.plot(kFFWB_center[start_fret:], exp_FFWB,'-',color =WBcolor,alpha = alpha2, linewidth=2)#, xlim=([minf-0.1, maxf+0.1]))

start_fret = 2
slope_n = start_fret+6
slope_WBSB = (kWBSB_hist_ln[start_fret]-kWBSB_hist_ln[slope_n])/(kWBSB_center[start_fret]-kWBSB_center[slope_n])
print( slope_WBSB, "slope", np.log(kWBSB_hist[start_fret]), "intercept")
intercept_WBSB = kWBSB_hist_ln[start_fret]-(slope_WBSB*exposure_time)
print( intercept_WBSB, "intercept adjusted WBSB")
kWBSBy = func_ln(kWBSB_center[start_fret:],intercept_WBSB, slope_WBSB)
popt_WBSB, pcov_WBSB = scipy.optimize.curve_fit(func_ln, kWBSB_center[start_fret:], kWBSBy)
exp_WBSB = func_ln(kWBSB_center[start_fret:],popt_WBSB[0],popt_WBSB[1])
plt.plot(kWBSB_center[start_fret:], exp_WBSB,'-',color =SBcolor,alpha = alpha2, linewidth=2)#, xlim=([minf-0.1, maxf+0.1]))

start_fret = 1
slope_n = start_fret+10
slope_WBFF = (kWBFF_hist_ln[start_fret]-kWBFF_hist_ln[slope_n])/(kWBFF_center[start_fret]-kWBFF_center[slope_n])
print( slope_WBFF, "slope", np.log(kWBFF_hist[start_fret]), "intercept")
intercept_WBFF = kWBFF_hist_ln[start_fret]-(slope_WBFF*exposure_time)
print( intercept_WBFF, "intercept adjusted WBFF")
kWBFFy = func_ln(kWBFF_center[start_fret:],intercept_WBFF, slope_WBFF)
popt_WBFF, pcov_WBFF = scipy.optimize.curve_fit(func_ln, kWBFF_center[start_fret:], kWBFFy)
exp_WBFF = func_ln(kWBFF_center[start_fret:],popt_WBFF[0],popt_WBFF[1])
plt.plot(kWBFF_center[start_fret:], exp_WBFF,'-',color =FFcolor,alpha = alpha2, linewidth=2)#, xlim=([minf-0.1, maxf+0.1]))

start_fret = 2
slope_n = start_fret+6
slope_SBWB = (kSBWB_hist_ln[start_fret]-kSBWB_hist_ln[slope_n])/(kSBWB_center[start_fret]-kSBWB_center[slope_n])
print( slope_SBWB, "slope")
intercept_SBWB = kSBWB_hist_ln[start_fret]-(slope_SBWB*exposure_time)
print( intercept_SBWB, "intercept adjusted SBWB")
kSBWBy = func_ln(kSBWB_center[start_fret:],intercept_SBWB, slope_SBWB)
popt_SBWB, pcov_SBWB = scipy.optimize.curve_fit(func_ln, kSBWB_center[start_fret:], kSBWBy)
exp_SBWB = func_ln(kSBWB_center[start_fret:],popt_SBWB[0],popt_SBWB[1])
plt.plot(kSBWB_center[start_fret:], exp_SBWB,'-',color =Tcolor,alpha = alpha2, linewidth=2)#, xlim=([minf-0.1, maxf+0.1]))

import matplotlib as mpl
mpl.rcParams['svg.fonttype'] = 'none'

#plt.figure()
#plt.plot(kSBWB, kSBWB_force)

UF 0.873529411765 0.250041086589
FF 0.663559322034 0.101423414682
WB 0.490740740741 0.0411103682136
SB 0.237058823529 0.0206419169876
kSBWB 0.230985915493 0.0252824327472
kWBSB 0.505056179775 0.0697564571893
kWBFF 0.495238095238 0.0549384144302
kFFWB 0.560416666667 0.0842338948981
kFFUF 2.125 1.33564903075
kUFFF 1.1375 0.471201920624
[0 0 2 0 0 1 1 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 1 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
-5.68249364079 slope
14.6145843009 intercept adjusted SBWB
-0.940007258491 slope 2.07944154168 intercept
8.38497911575 intercept adjusted WBFF
-0.743811837714 slope 2.30258509299 intercept
10.3789081556 intercept adjusted WBSB
-5.34000426693 slope 2.94443897917 intercept
24.8147737744 intercept adjusted FFWB
8 96 84 89 71
('kFFWB=', '5.34', '$\t{s^{-1}}$', 187.0, 'ms')
('kWBSB=', '0.7438', '$\t{s^{-1}}$', 1344.0, 'ms')
('kWBFF=', '0.94', '$\t{s^{-1}}$', 1064

In [406]:
#n_values = []
#chi2 = []
#n_values.pop(-1)
#chi2.pop(-1)
n_values.append((n_states))
chi2.append((float(chisq_value)))

print(n_values, chi2)

[4, 5, 6, 7] [592.6657199078592, 567.9239541413084, 287.11849646388276, 489.1403233877729]


In [407]:
def exp_decay(t, A, k,c):
    return A*np.exp(-k*t)+ c
    

In [408]:
plt.close('all')
plt.figure("Chi squared for "+str(refoldtime)+ " seconds")
plt.scatter(n_values, chi2)
print(n_values,np.array(chi2))
popt, pcov = scipy.optimize.curve_fit(exp_decay, n_values, chi2, p0=(105, 1, 11))
print(n_values, *popt)
#popt = [50, 0.5]
y_fit = []
for i in n_values:
    y_fit.append(exp_decay(i,*popt))
    
print(y_fit)
plt.plot(n_values,y_fit)
plt.annotate("y = "+str(np.round(popt[0],2))+" * e^(-" +str(np.round(popt[1],2))+" * t) + " + str(np.round(popt[2],2)),(4,25))

[4, 5, 6, 7] [ 592.66571991  567.92395414  287.11849646  489.14032339]
[4, 5, 6, 7] 6187.51250411 0.841418115695 393.542655835
[607.25180295402038, 485.67240027991852, 433.25967275208848, 410.66461185784937]


In [434]:
np.save("chi squared for " + str(refoldtime) + " seconds"+".npy", [n_values,chi2, popt])

In [61]:
plt.figure()
#print(len(Time2),(X2))
plt.scatter(np.array(Time2), np.array(X2))
plt.ylim(0,1)
print(fret_list)

['2014.09.03_WT2at_200pM_s1m5_refold_0.5s_1.fret', '2014.09.03_WT2at_200pM_s1m5_refold_0.5s_2.fret', '2014.09.03_WT2at_200pM_s1m5_refold_0.5s_3.fret', '2014.09.03_WT2at_200pM_s1m5_refold_0.5s_4.fret', '2014.09.03_WT2at_200pM_s1m5_refold_0.5s_5.fret', '2014.09.03_WT2at_200pM_s1m5_refold_0.5s_6.fret', '2014.09.15_WT2at_100pM_s1m3_refold_0.5s_1.fret', '2014.09.15_WT2at_100pM_s1m3_refold_0.5s_2.fret', '2014.09.15_WT2at_100pM_s1m3_refold_0.5s_3.fret', '2014.10.23_WT2at_200pM_s2m2_refold_0.5s_3.fret', '2014.10.23_WT2at_200pM_s2m2_refold_0.5s_4.fret', '2014.10.29_WT2at_200pM_s1m2_refold_0.5s_1.fret', '2014.10.29_WT2at_200pM_s1m5_refold_0.5s_1.fret', '2014.11.03_WT2at_100pM_s2m2_refold_0.5s_1.fret', '2014.11.03_WT2at_100pM_s2m2_refold_0.5s_2.fret', '2014.11.03_WT2at_100pM_s2m2_refold_0.5s_3.fret', '2014.11.03_WT2at_100pM_s2m2_refold_0.5s_4.fret', '2014.11.03_WT2at_100pM_s2m2_refold_0.5s_5.fret', '2014.11.03_WT2at_100pM_s2m2_refold_0.5s_6.fret', '2014.11.04_WT2at_100pM_s1m1_refold_0.5s_1.fret',

In [409]:
#print (len(X), len(X[0]))
#print (model.populations_)#, model.predict(X), model.get_params())
predict = model.predict(X)
#print(predict)
predict_vectors = predict[1][0]
predict_vectors= predict_vectors
#print(len(predict_vectors), "love")
P_0 = []
P_1 = []
P_2 = []
P_3 = []
p_new = list()
p_count = 0
for i,p in enumerate(predict_vectors[:-1]):   
    if predict_vectors[i] == predict_vectors[i+1] and i !=len(predict_vectors)-2:
        p_count += 1
        #print(p_count, i)

    elif predict_vectors[i] != predict_vectors[i+1] or i ==len(predict_vectors)-2:
        if predict_vectors[i] == 0:
            p_count += 1
            #print(p_count,predict_vectors[i],"0-teen")
            P_0.append(p_count * float(0.050))
                    #break
        elif predict_vectors[i] == 1:
            p_count += 1
            #print(p_count,predict_vectors[i],"1-teen")
            P_1.append(p_count * float(0.050))
                    #break
        elif predict_vectors[i] == 2:
            p_count += 1
            #print(p_count,predict_vectors[i],"2-teen")
            P_2.append(p_count * float(0.050))
                    #break
        elif predict_vectors[i]:
            #print(p_count, 'love')
            break
    
        p_count = 0

            
_0 = "FF"
_1 = "WB"
_2 = "SB"
print(len(P_0),len(P_1),len(P_2), P_0)  
print(str(_2)+" = ",np.mean(P_0),"\n",
      str(_1)+" = ",np.mean(P_1),"\n",
      str(_0)+" = ",np.mean(P_2),"\n")
        
            
print('n_states=%d\ttimescales=%s' % (n_states,  timescales))


0 0 0 []
SB =  nan 
 WB =  nan 
 FF =  nan 

n_states=7	timescales=[array([ 13.86999798,   6.33793545,   3.07756233,   0.54736865], dtype=float32)]


c:\Users\vknguyen\AppData\Local\Continuum\Anaconda3\lib\site-packages\numpy\core\_methods.py:59: RuntimeWarning: Mean of empty slice.
  warnings.warn("Mean of empty slice.", RuntimeWarning)


In [194]:
#SB_dwell_times = []
#WB_dwell_times = []
#FF_dwell_times = []

In [453]:
SB_dwell_times.append(np.mean(P_2))
WB_dwell_times.append(np.mean(P_1))
FF_dwell_times.append(np.mean(P_0))
print(len(SB_dwell_times))

15


In [454]:
print(np.mean(SB_dwell_times),
      np.mean(WB_dwell_times),
      np.mean(FF_dwell_times))

0.318060846561 0.238428571429 0.420793650794


In [ ]:
plt.hist(SB_dwell_times, bin = 10)


#TS = msmbuilder.msm.ContinuousTimeMSM(X)
#TS = msmbuilder.msm.implied_timescales()
#print(TS.populations_, TS.fit)
